export default {
  kind: 'customsearch#search',
  url: {
    type: 'application/json',
    template: 'https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json',
  },
  queries: {
    request: [
      {
        title: 'Google Custom Search - Drums',
        totalResults: '4150000',
        searchTerms: 'Drums',
        count: 10,
        startIndex: 1,
        inputEncoding: 'utf8',
        outputEncoding: 'utf8',
        safe: 'off',
        cx: 'd75ab8958d28077bc',
      },
    ],
    nextPage: [
      {
        title: 'Google Custom Search - Drums',
        totalResults: '4150000',
        searchTerms: 'Drums',
        count: 10,
        startIndex: 11,
        inputEncoding: 'utf8',
        outputEncoding: 'utf8',
        safe: 'off',
        cx: 'd75ab8958d28077bc',
      },
    ],
  },
  context: {
    title: 'Google',
  },
  searchInformation: {
    searchTime: 0.481071,
    formattedSearchTime: '0.48',
    totalResults: '4150000',
    formattedTotalResults: '4,150,000',
  },
  items: [
    {
      kind: 'customsearch#result',
      title: 'Charlie Watts Plays Air Drums During Rolling Stones Performance ...',
      htmlTitle: 'Charlie Watts Plays Air <b>Drums</b> During Rolling Stones Performance ...',
      link: 'https://www.google.com/appserve/mkt/p/AM7kBiVpYRyAGA4ML9NJkA2ytssWdBN-TiCwkSn7bkYF6n9mX9VGIz2l5czEM_YBTKgC8sblklxvmFdZWrPP9pBk-oCHXj1KRHeZRJionEz7Ap60mvGMfHfSzTL3MS6cOn3zyCPoOFNvSfa3H6Q',
      displayLink: 'www.google.com',
      snippet: 'Apr 18, 2020 ... The Rolling Stones took part in One World: Together at Home performing their \niconic song "You Can\'t Always Get What You Want," but it was ...',
      htmlSnippet: 'Apr 18, 2020 <b>...</b> The Rolling Stones took part in One World: Together at Home performing their <br>\niconic song &quot;You Can&#39;t Always Get What You Want,&quot; but it was&nbsp;...',
      cacheId: 'YHwqJ3uxEO0J',
      formattedUrl: 'https://www.google.com/.../AM7kBiVpYRyAGA4ML9NJkA2ytssWdBN- TiCwkSn7bkYF6n9mX9VGIz2l5czEM_YBTKgC8sblklxvmFdZWrPP9pB...',
      htmlFormattedUrl: 'https://www.google.com/.../AM7kBiVpYRyAGA4ML9NJkA2ytssWdBN- TiCwkSn7bkYF6n9mX9VGIz2l5czEM_YBTKgC8sblklxvmFdZWrPP9pB...',
      pagemap: {
        cse_thumbnail: [
          {
            src: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQqjLN7tJmyxvQLdEUZQzxev8_lNRU8amVPUNdx37tMQsJrIPuWZoh8HB0',
            width: '258',
            height: '195',
          },
        ],
        organization: [
          {
            logo: 'https://wmmr.com/wp-content/uploads/sites/15/2019/06/wmmr-logo-616x352-1.png?width=154&height=88&anchor=middlecenter',
            url: 'https://wmmr.com/',
          },
        ],
        metatags: [
          {
            'og:image': 'https://wmmr.com/wp-content/uploads/sites/15/2020/04/GettyImages-1219649138-e1587261238883-1.jpg',
            'article:published_time': '2020-04-18T21:27:17-04:00',
            'og:image:width': '1555',
            'twitter:card': 'summary_large_image',
            'og:site_name': '93.3 WMMR',
            'tec-api-origin': 'https://wmmr.com',
            'og:description': 'The Rolling Stones took part in One World: Together at Home performing their iconic song "You Can\'t Always Get What You Want," but it was drummer Charlie Watts\' "performance" that got a lot of attention.',
            'twitter:creator': '@933wmmr',
            'article:publisher': 'http://facebook.com/933WMMRFM',
            'og:image:secure_url': 'https://wmmr.com/wp-content/uploads/sites/15/2020/04/GettyImages-1219649138-e1587261238883-1.jpg',
            'twitter:image': 'https://wmmr.com/wp-content/uploads/sites/15/2020/04/GettyImages-1219649138-e1587261238883-1.jpg?width=600&maxheight=314&anchor=middlecenter&mode=crop',
            'parsely-network-canonical': 'https://content.bbgi.com/charlie-watts-air-drumming/',
            'twitter:site': '@933wmmr',
            'article:modified_time': '2020-04-20T10:32:00-04:00',
            'tec-api-version': 'v1',
            'lytics:author': 'ebanas',
            'og:type': 'article',
            'article:section': '93.3 WMMR',
            'twitter:title': "Charlie Watts Plays Air Drums During Rolling Stones Performance on 'One World: Together at Home'",
            'wp-parsely_version': '2.2.1',
            'lytics:topics': 'Preston and Steve, Rock News, 933 WMMR, Music, Rock News',
            'og:title': "Charlie Watts Plays Air Drums During Rolling Stones Performance on 'One World: Together at Home'",
            'og:image:height': '1174',
            'og:updated_time': '2020-04-20T10:32:00-04:00',
            'article:author': 'https://wmmr.com/author/ebanas/',
            'article:tag': 'Charlie Watts',
            'fb:app_id': '347087535362665',
            viewport: 'width=device-width, initial-scale=1',
            'twitter:description': 'The Rolling Stones took part in One World: Together at Home performing their iconic song "You Can\'t Always Get What You Want," but it was drummer Charlie Watts\' "performance" that got a lot of attention.',
            'og:locale': 'en_US',
            'og:url': 'https://wmmr.com/2020/04/18/charlie-watts-air-drumming-2/',
          },
        ],
        cse_image: [
          {
            src: 'https://wmmr.com/wp-content/uploads/sites/15/2020/04/GettyImages-1219649138-e1587261238883-1.jpg',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Drums & Flats Ltd - Google Maps',
      htmlTitle: '<b>Drums</b> &amp; Flats Ltd - Google Maps',
      link: 'https://www.google.com/maps/search/?api=1&query=Drums+%26+Flats+Ltd&query_place_id=ChIJIQBNTqADdkgR44HynQ5FF5A',
      displayLink: 'www.google.com',
      snippet: 'Drums & Flats Ltd. Your location. Trails. Dedicated lanes. Bicycle-friendly roads. \nDirt/unpaved trails. Live traffic. Fast. Slow. 2000 km. Set depart & arrive time.',
      htmlSnippet: '<b>Drums</b> &amp; Flats Ltd. Your location. Trails. Dedicated lanes. Bicycle-friendly roads. <br>\nDirt/unpaved trails. Live traffic. Fast. Slow. 2000 km. Set depart &amp; arrive time.',
      cacheId: 'nhwllpwqZZsJ',
      formattedUrl: 'https://www.google.com/maps/search/?api=1&query=Drums...id...',
      htmlFormattedUrl: 'https://www.google.com/maps/search/?api=1&amp;query=<b>Drums</b>...id...',
      pagemap: {
        cse_thumbnail: [
          {
            src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQUDTMfgWSotdHvbOKW4AmY1steqsilnDJS4q33zGx-d0AXvvxPiFY9Mvs',
            width: '204',
            height: '247',
          },
        ],
        metatags: [
          {
            referrer: 'origin',
            'twitter:card': 'summary',
            'theme-color': '#3367d6',
            viewport: 'initial-scale=1.0, user-scalable=no',
            google: 'notranslate',
          },
        ],
        cse_image: [
          {
            src: 'https://maps.gstatic.com/tactile/basepage/pegman_sherlock.png',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Urban Tribe Events (Dubai Drums), Dubai, ae - Google Maps',
      htmlTitle: 'Urban Tribe Events (Dubai <b>Drums</b>), Dubai, ae - Google Maps',
      link: 'https://www.google.com/maps/search/?api=1&query=Urban+Tribe+Events+%28Dubai+Drums%29%2C+Dubai%2C+ae&query_place_id=ChIJNb4dpVtpXz4RY8GILNH5bxU',
      displayLink: 'www.google.com',
      snippet: 'Urban Tribe Events (Dubai Drums), Dubai, ae. Your location. Trails. Dedicated \nlanes. Bicycle-friendly roads. Dirt/unpaved trails. Live traffic. Fast. Slow. 1000 km.',
      htmlSnippet: 'Urban Tribe Events (Dubai <b>Drums</b>), Dubai, ae. Your location. Trails. Dedicated <br>\nlanes. Bicycle-friendly roads. Dirt/unpaved trails. Live traffic. Fast. Slow. 1000 km.',
      cacheId: 'jSVPuTvbh2QJ',
      formattedUrl: 'https://www.google.com/maps/search/?api...Drums%29%2C...',
      htmlFormattedUrl: 'https://www.google.com/maps/search/?api...<b>Drums</b>%29%2C...',
      pagemap: {
        cse_thumbnail: [
          {
            src: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQUDTMfgWSotdHvbOKW4AmY1steqsilnDJS4q33zGx-d0AXvvxPiFY9Mvs',
            width: '204',
            height: '247',
          },
        ],
        metatags: [
          {
            referrer: 'origin',
            'twitter:card': 'summary',
            'theme-color': '#3367D6',
            viewport: 'initial-scale=1.0, user-scalable=no',
            google: 'notranslate',
          },
        ],
        cse_image: [
          {
            src: 'https://maps.gstatic.com/tactile/basepage/pegman_sherlock.png',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Sugarloaf Drums Ln - Google Maps',
      htmlTitle: 'Sugarloaf <b>Drums</b> Ln - Google Maps',
      link: 'https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=40.997108,-76.051339',
      displayLink: 'www.google.com',
      snippet: 'Find local businesses, view maps and get driving directions in Google Maps.',
      htmlSnippet: 'Find local businesses, view maps and get driving directions in Google Maps.',
      cacheId: 'E-i9Vx9C1xkJ',
      formattedUrl: 'https://www.google.com/maps/@?api=1&map_action=pano...40...',
      htmlFormattedUrl: 'https://www.google.com/maps/@?api=1&amp;map_action=pano...40...',
      pagemap: {
        metatags: [
          {
            referrer: 'origin',
            'og:image': 'https://maps.google.com/maps/api/staticmap?center=40.997108%2C-76.051339&zoom=-1&size=256x256&language=en&sensor=false&client=google-maps-frontend&signature=gZ4tkBpSEfVoDbtoajigTMuFIvM',
            'og:image:width': '256',
            'twitter:card': 'summary',
            'og:site_name': 'Google Maps',
            viewport: 'initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no',
            'og:title': 'Google Maps',
            'og:image:height': '256',
            google: 'notranslate',
            'og:description': 'Find local businesses, view maps and get driving directions in Google Maps.',
          },
        ],
        place: [
          {
            image: 'https://maps.google.com/maps/api/staticmap?center=40.997108%2C-76.051339&zoom=-1&size=256x256&language=en&sensor=false&client=google-maps-frontend&signature=gZ4tkBpSEfVoDbtoajigTMuFIvM',
            name: 'Google Maps',
            description: 'Find local businesses, view maps and get driving directions in Google Maps.',
          },
        ],
        cse_image: [
          {
            src: 'https://maps.google.com/maps/api/staticmap?center=40.997108%2C-76.051339&zoom=-1&size=256x256&language=en&sensor=false&client=google-maps-frontend&signature=gZ4tkBpSEfVoDbtoajigTMuFIvM',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'drum to death',
      htmlTitle: '<b>drum</b> to death',
      link: 'https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy80M2NkM2JmNC9wb2RjYXN0L3Jzcw==',
      displayLink: 'www.google.com',
      snippet: "drum to death is about the intangible. it's about the undying pursuit toward \naccomplishing a goal or perfecting a craft. drum to death has almost nothing to do \nwith ...",
      htmlSnippet: '<b>drum</b> to death is about the intangible. it&#39;s about the undying pursuit toward <br>\naccomplishing a goal or perfecting a craft. <b>drum</b> to death has almost nothing to do <br>\nwith&nbsp;...',
      cacheId: 'Xo1O3VsKJ_0J',
      formattedUrl: 'https://www.google.com/podcasts?feed...',
      htmlFormattedUrl: 'https://www.google.com/podcasts?feed...',
      pagemap: {
        metatags: [
          {
            'og:image': 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR7fgGiVzMDK5kGW2dQAAR8p4fBPGa2k3altHBgT8xbI9Yh7p3t',
            'apple-itunes-app': 'app-id=1398000105, affiliate-data=ct=podcastsSmartBannerShow001&pt=9008, app-argument=https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy80M2NkM2JmNC9wb2RjYXN0L3Jzcw',
            'og:type': 'music.radio_station',
            'twitter:card': 'summary',
            'twitter:title': 'drum to death',
            'og:site_name': 'Google Podcasts',
            'og:title': 'drum to death',
            'music:creator': 'drum to death',
            title: 'drum to death',
            'og:description': 'drum to death is about the intangible. it’s about the undying pursuit toward accomplishing a goal or perfecting a craft. drum to death has almost nothing to do with drums, but what the drums represent for each of us. following your passion with every fiber of your being, for fulfillment or personal betterment, is akin to a cult or religion. this is the sole inspiration for drum to death. drum to death in and of itself is an ethos. it is an unadulterated commitment to a craft that extends far beyond that of a hobby.',
            'twitter:creator': 'drum to death',
            'article:author': 'drum to death',
            'twitter:image': 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR7fgGiVzMDK5kGW2dQAAR8p4fBPGa2k3altHBgT8xbI9Yh7p3t',
            referrer: 'origin',
            viewport: 'width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,minimal-ui',
            'og:url': 'https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy80M2NkM2JmNC9wb2RjYXN0L3Jzcw',
          },
        ],
        cse_image: [
          {
            src: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR7fgGiVzMDK5kGW2dQAAR8p4fBPGa2k3altHBgT8xbI9Yh7p3t',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'US974964A - Method of and means for supporting rotary drums ...',
      htmlTitle: 'US974964A - Method of and means for supporting rotary <b>drums</b> ...',
      link: 'https://www.google.com/patents/US974964',
      displayLink: 'www.google.com',
      snippet: 'Such a rotary drum, owing to the action of gravity would move downward during \nrotation if the axes of the supporting rollers were not inclinedat a small angle to ...',
      htmlSnippet: 'Such a rotary <b>drum</b>, owing to the action of gravity would move downward during <br>\nrotation if the axes of the supporting rollers were not inclinedat a small angle to&nbsp;...',
      formattedUrl: 'https://www.google.com/patents/US974964',
      htmlFormattedUrl: 'https://www.google.com/patents/US974964',
      pagemap: {
        metatags: [
          {
            referrer: 'origin-when-crossorigin',
            citation_patent_application_number: 'US:46876808A',
            citation_patent_number: 'US:974964',
            'dc.type': 'patent',
            viewport: 'width=device-width, initial-scale=1',
            'dc.title': 'Method of and means for supporting rotary drums.',
            citation_pdf_url: 'https://patentimages.storage.googleapis.com/49/b4/fe/f475af230a47d2/US974964.pdf',
            'dc.date': '1908-12-22',
            'dc.contributor': 'Albin Berthold Helbig',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'WO2014001830A2 - Concrete mixer drums and constructions ...',
      htmlTitle: 'WO2014001830A2 - Concrete mixer <b>drums</b> and constructions ...',
      link: 'http://www.google.com/patents/WO2014001830A2?cl=en',
      displayLink: 'www.google.com',
      snippet: 'The invention relates to concrete mixer drums and constructions thereof, in \nparticular colored concrete mixers, made of a light metal alloy, in particular made \nof ...',
      htmlSnippet: 'The invention relates to concrete mixer <b>drums</b> and constructions thereof, in <br>\nparticular colored concrete mixers, made of a light metal alloy, in particular made <br>\nof&nbsp;...',
      formattedUrl: 'www.google.com/patents/WO2014001830A2?cl=en',
      htmlFormattedUrl: 'www.google.com/patents/WO2014001830A2?cl=en',
      pagemap: {
        metatags: [
          {
            referrer: 'origin-when-crossorigin',
            citation_patent_application_number: 'PC:T/IB2012/001256',
            'dc.description': 'The invention relates to concrete mixer drums and constructions thereof, in particular colored concrete mixers, made of a light metal alloy, in particular made of an aluminum alloy.',
            citation_patent_publication_number: 'WO:2014001830:A2',
            'dc.type': 'patent',
            citation_reference: 'None',
            viewport: 'width=device-width, initial-scale=1',
            'dc.title': 'Concrete mixer drums and constructions thereof',
            'dc.date': '2012-06-25',
            'dc.contributor': 'Walter WAX',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'US627766A - Drum. - Google Patents',
      htmlTitle: 'US627766A - <b>Drum</b>. - Google Patents',
      link: 'https://www.google.com/patents/US627766',
      displayLink: 'www.google.com',
      snippet: 'DRUM. (Application filed Apr. 1, 1899.) (No Model.) UNITE STAT S PATENT \nOFFICE. GEORGE IVILKEN, OF NEIV YORK, N. Y..',
      htmlSnippet: '<b>DRUM</b>. (Application filed Apr. 1, 1899.) (No Model.) UNITE STAT S PATENT <br>\nOFFICE. GEORGE IVILKEN, OF NEIV YORK, N. Y..',
      formattedUrl: 'https://www.google.com/patents/US627766',
      htmlFormattedUrl: 'https://www.google.com/patents/US627766',
      pagemap: {
        metatags: [
          {
            referrer: 'origin-when-crossorigin',
            citation_patent_number: 'US:627766',
            'dc.type': 'patent',
            viewport: 'width=device-width, initial-scale=1',
            'dc.title': 'Drum.',
            citation_pdf_url: 'https://patentimages.storage.googleapis.com/b0/07/36/95e7781da84bf9/US627766.pdf',
            'dc.date': '1899-04-01',
            'dc.contributor': 'George Wilken',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'US2695109A - Drum handling hand truck equipment - Google Patents',
      htmlTitle: 'US2695109A - <b>Drum</b> handling hand truck equipment - Google Patents',
      link: 'https://www.google.com/patents/US2695109',
      displayLink: 'www.google.com',
      snippet: 'PRINGLE, JR 5 9 DRUM HANDLING HAND TRUCK EQUIPMENT Filed July 5, ... \n(Cl. 214-383) In the handling of drums such as used for oil and chemicals, ...',
      htmlSnippet: 'PRINGLE, JR 5 9 <b>DRUM</b> HANDLING HAND TRUCK EQUIPMENT Filed July 5, ... <br>\n(Cl. 214-383) In the handling of <b>drums</b> such as used for oil and chemicals,&nbsp;...',
      formattedUrl: 'https://www.google.com/patents/US2695109',
      htmlFormattedUrl: 'https://www.google.com/patents/US2695109',
      pagemap: {
        metatags: [
          {
            referrer: 'origin-when-crossorigin',
            citation_patent_application_number: 'US:2/352,00A',
            citation_patent_number: 'US:2695109',
            'dc.type': 'patent',
            viewport: 'width=device-width, initial-scale=1',
            'dc.relation': 'US:349665',
            'dc.title': 'Drum handling hand truck equipment',
            citation_pdf_url: 'https://patentimages.storage.googleapis.com/3e/ac/e7/53dec3c1cf1c47/US2695109.pdf',
            'dc.date': '1951-07-05',
            'dc.contributor': 'Jr Robert S Pringle',
          },
        ],
      },
    },
    {
      kind: 'customsearch#result',
      title: 'WO1993007431A1 - Rotary drum dryer having internal flights ...',
      htmlTitle: 'WO1993007431A1 - Rotary <b>drum</b> dryer having internal flights ...',
      link: 'https://www.google.com/patents/WO1993007431A1?cl=zh-CN',
      displayLink: 'www.google.com',
      snippet: 'US4600379A 1986-07-15 Drum heating and mixing apparatus and method ... \nMethod and apparatus for reducing smoke emissions in an asphalt drum mixer.',
      htmlSnippet: 'US4600379A 1986-07-15 <b>Drum</b> heating and mixing apparatus and method ... <br>\nMethod and apparatus for reducing smoke emissions in an asphalt <b>drum</b> mixer.',
      formattedUrl: 'https://www.google.com/patents/WO1993007431A1?cl=zh-CN',
      htmlFormattedUrl: 'https://www.google.com/patents/WO1993007431A1?cl=zh-CN',
      pagemap: {
        metatags: [
          {
            referrer: 'origin-when-crossorigin',
            citation_patent_application_number: 'PC:T/US1992/008373',
            citation_patent_publication_number: 'WO:1993007431:A1',
            'dc.type': 'patent',
            viewport: 'width=device-width, initial-scale=1',
            'dc.relation': 'BE:565990:A',
            'dc.title': 'Rotary drum dryer having internal flights',
            citation_pdf_url: 'https://patentimages.storage.googleapis.com/b2/20/41/9bd5a4eea5ab2b/WO1993007431A1.pdf',
            'dc.date': '1992-09-30',
            'dc.contributor': 'Malcolm L. Swanson',
          },
        ],
      },
    },
  ],
};
